#!/usr/bin/perl
# Copyright (C) 2006  Alex Schroeder <alex@emacswiki.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
#    Free Software Foundation, Inc.
#    59 Temple Place, Suite 330
#    Boston, MA 02111-1307 USA
my $FS  = "\x1e";
my %Total = ();
my %Month = ();
while (<STDIN>) {
  my ($ts, $pagename, $minor, $summary, $host, $username, $revision,
      $languages, $cluster)
    = split(/$FS/);
  my ($sec, $min, $hour, $mday, $mon, $year) = gmtime($ts);
  my $key = sprintf("%d-%02d", 1900 + $year, $mon + 1);
  # $username = 'Anon' unless $username;
  $Total{$key}++;
  $Month{$key}{$username}++ if $username;
}
print "Month   Total    Top Poster     Edits\n";
for my $key (sort keys %Total) {
  my @posters = keys %{$Month{$key}};
  @posters = sort { $Month{$key}{$b} <=> $Month{$key}{$a} } @posters;
  my $top = shift @posters;
  printf("%s  %6d  %20s  %5d\n", $key, $Total{$key},
          $top, $Month{$key}{$top});
}
