#! /usr/bin/perl
# Copyright (C) 2005  Alex Schroeder <alex@emacswiki.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
#    Free Software Foundation, Inc.
#    59 Temple Place, Suite 330
#    Boston, MA 02111-1307 USA

use Getopt::Std;
use LWP::UserAgent;

our $opt_b;
getopt('b');
my $base = $opt_b;
my $url = shift;
die "Usage: wikipipe [-b base-url] url\n" unless $url;
undef $/;

my $data = <STDIN>;
my $ua = new LWP::UserAgent;
my %params = (action=>raw, data=>$data, base=>$base);
my $response = $ua->post($url, \%params);
die $response->status_line unless $response->is_success;
print $response->content;
