#!/bin/bash
# Copyright (C) 2014-2015  Alex-Daniel Jakimenko <alex.jakimenko@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

# This script parses every link and gets the total number of modules
# Use this script like this: ./module-popularity < list | tee popularity
# Where 'list' is a file with a list of links to action=version (one link on each line)

MODULES_PATH='../modules/'
S='||' # table separator

declare -A modules
declare -A moduleLinks

while read -r link; do
    echo "$link"
    while read -r module; do
	[[ $module == 'wiki.pl' ]] && continue
	((modules["$module"] += 1))
	moduleLinks["$module"]+=" $link";
    done < <(curl -s "$link" | grep -Po 'tree/modules/\K.*?\.pl|\$Id:\s*\K.*?\.pl')
done


for curModule in "${!modules[@]}"; do
    if [[ -f "$MODULES_PATH/$curModule" ]]; then
	usefulLinks="Module:$curModule $S"
	wikiPage=$(grep -Po "AddModuleDescription\('[^']+',\s*'\K[^']+" "$MODULES_PATH/$curModule")
	if [[ $wikiPage ]]; then
	    usefulLinks+="[[$wikiPage]]"
	else
	    usefulLinks+='No wiki page'
	fi
    else
	usefulLinks="${S} Custom module"
    fi
    echo "$S ${modules[$curModule]} $S$curModule $S$usefulLinks $S ${moduleLinks[$curModule]} $S"
done | sort -k 3 | sort -nrsk 2
