#!/usr/bin/perl
# traffic -- summarize bandwidth usage
# Copyright (C) 2006  Alex Schroeder <alex@emacswiki.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
#    Free Software Foundation, Inc.
#    59 Temple Place, Suite 330
#    Boston, MA 02111-1307 USA
#
# $Id: traffic,v 1.2 2006/09/01 11:14:34 as Exp $</p>'

while (<STDIN>) {
  # 304 responses have - as bytes
  $bytes += $1 if m/\[.*?\] ".*?" \d+ (\d+)/;
}
printf "%d %dK %.1fM %.2fG\n", $bytes, $bytes/1024, $bytes/1024000, $bytes/1024000000;
